name: My Workflow
on: push
    
jobs:
  run-groovy-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
      - name: Install Groovy
        run: |
          curl -s get.sdkman.io | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install groovy
      - name: Run Groovy script
        run: groovy myScript.groovy
